-- Run this in Supabase Dashboard → SQL Editor.
-- Adds two-tier auth: a "complex" (plaza/landlord) admin account that owns a
-- set of businesses, and an optional login per business so each tenant can
-- see only their own bill history.
--
-- IMPORTANT — READ FIRST:
-- 1. This assumes `businesses`, `billing_cycles`, and `cycle_business_bills`
--    already exist (from the earlier migrations). If you have NOT yet run
--    those, run supabase-migration.sql first.
-- 2. If `businesses` currently has any permissive "allow all" policies from
--    before (open access, no auth), DROP them before running this — open
--    policies and the scoped ones below can conflict. Check:
--    Dashboard → Authentication → Policies → businesses.
-- 3. This changes `businesses.id` to auto-generate from a sequence instead
--    of being assigned by the app. If you already have businesses saved,
--    this migration advances the sequence past your current max id so new
--    rows won't collide — but please back up your data first regardless.
-- 4. After running this, your EXISTING businesses/billing_cycles/
--    cycle_business_bills rows will have complex_id = null, which means
--    they become invisible under the new policies until you assign them to
--    a complex. Steps for that are at the bottom of this file.

-- ============================================================
-- 1. Complexes (one per client / plaza)
-- ============================================================
create table if not exists complexes (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null unique references auth.users(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now()
);

alter table complexes enable row level security;

drop policy if exists "owner can read own complex" on complexes;
create policy "owner can read own complex" on complexes
  for select using (owner_id = auth.uid());

drop policy if exists "owner can update own complex" on complexes;
create policy "owner can update own complex" on complexes
  for update using (owner_id = auth.uid());

drop policy if exists "user can create their own complex" on complexes;
create policy "user can create their own complex" on complexes
  for insert with check (owner_id = auth.uid());

-- ============================================================
-- 2. Businesses — scope to a complex, allow a login to be linked
-- ============================================================
alter table businesses
  add column if not exists complex_id uuid references complexes(id) on delete cascade,
  add column if not exists email text,
  add column if not exists owner_user_id uuid references auth.users(id);

create unique index if not exists idx_businesses_complex_email
  on businesses (complex_id, email) where email is not null;

-- Make `id` auto-generate instead of being assigned by the app (needed now
-- that many complexes share this one table). Skip this block if `id` is
-- already an identity/serial column.
do $$
begin
  if not exists (
    select 1 from pg_attribute a
    join pg_class c on c.oid = a.attrelid
    where c.relname = 'businesses' and a.attname = 'id' and a.attidentity <> ''
  ) then
    alter table businesses alter column id add generated by default as identity;
    perform setval(
      pg_get_serial_sequence('businesses', 'id'),
      coalesce((select max(id) from businesses), 0) + 1,
      false
    );
  end if;
end $$;

alter table businesses enable row level security;

-- Drop any old open-access policy from before auth existed:
-- drop policy if exists "Allow all for anon" on businesses;

drop policy if exists "admin manages own complex businesses" on businesses;
create policy "admin manages own complex businesses" on businesses
  for all using (
    complex_id in (select id from complexes where owner_id = auth.uid())
  ) with check (
    complex_id in (select id from complexes where owner_id = auth.uid())
  );

drop policy if exists "business owner reads own row" on businesses;
create policy "business owner reads own row" on businesses
  for select using (owner_user_id = auth.uid());

drop policy if exists "business owner claims own row" on businesses;
create policy "business owner claims own row" on businesses
  for update using (email = auth.email() and owner_user_id is null)
  with check (owner_user_id = auth.uid());

-- ============================================================
-- 3. Billing cycles — admin-only, scoped to their complex
-- ============================================================
alter table billing_cycles
  add column if not exists complex_id uuid references complexes(id) on delete cascade;

alter table billing_cycles enable row level security;

-- drop policy if exists "Allow all for anon" on billing_cycles;

drop policy if exists "admin manages own complex cycles" on billing_cycles;
create policy "admin manages own complex cycles" on billing_cycles
  for all using (
    complex_id in (select id from complexes where owner_id = auth.uid())
  ) with check (
    complex_id in (select id from complexes where owner_id = auth.uid())
  );

-- ============================================================
-- 4. Cycle business bills — admin scoped, plus each business owner can
--    read (only) their own bill history
-- ============================================================
alter table cycle_business_bills
  add column if not exists complex_id uuid references complexes(id) on delete cascade;

alter table cycle_business_bills enable row level security;

-- drop policy if exists "Allow all for anon" on cycle_business_bills;

drop policy if exists "admin manages own complex cycle bills" on cycle_business_bills;
create policy "admin manages own complex cycle bills" on cycle_business_bills
  for all using (
    complex_id in (select id from complexes where owner_id = auth.uid())
  ) with check (
    complex_id in (select id from complexes where owner_id = auth.uid())
  );

drop policy if exists "business owner reads own bill history" on cycle_business_bills;
create policy "business owner reads own bill history" on cycle_business_bills
  for select using (
    business_id in (select id from businesses where owner_user_id = auth.uid())
  );

-- ============================================================
-- 5. One-time backfill for data that existed before this migration
-- ============================================================
-- Run this ONLY if you already had businesses saved before adding auth.
-- Sign up as the complex admin in the app first (this creates your
-- complexes row), then find your new complex id:
--
--   select id, name from complexes;
--
-- Then backfill your existing rows to that complex (replace the uuid):
--
--   update businesses set complex_id = '<your-complex-id>' where complex_id is null;
--   update billing_cycles set complex_id = '<your-complex-id>' where complex_id is null;
--   update cycle_business_bills set complex_id = '<your-complex-id>' where complex_id is null;
