-- Run this SECOND, after supabase-fix-rls-now.sql, to check whether the
-- id-auto-generation step from the original migration actually completed.

-- Step 1: check current state
select column_name, is_identity, identity_generation
from information_schema.columns
where table_name = 'businesses' and column_name = 'id';

-- If is_identity = 'YES': you're fine, nothing else to do here.

-- If is_identity = 'NO': the conversion never ran, and the app's
-- "Add Business" button will currently be broken (it no longer sends an
-- id, expecting the database to generate one). Run this to fix it:

alter table businesses alter column id add generated by default as identity;

select setval(
  pg_get_serial_sequence('businesses', 'id'),
  coalesce((select max(id) from businesses), 0) + 1,
  false
);

-- Step 2: confirm it worked
select column_name, is_identity, identity_generation
from information_schema.columns
where table_name = 'businesses' and column_name = 'id';
